function [segments_length] = CalSegmentsLength(streamInter)
    segments_length = struct();
    for i = 1:length(streamInter.wtime)
        segments_length.Thigh_Left(i) = norm([streamInter.HIP_LEFT.x(i),streamInter.HIP_LEFT.y(i),streamInter.HIP_LEFT.z(i)]-...
            [streamInter.KNEE_LEFT.x(i),streamInter.KNEE_LEFT.y(i),streamInter.KNEE_LEFT.z(i)]);
        segments_length.Shank_Left(i) = norm([streamInter.KNEE_LEFT.x(i),streamInter.KNEE_LEFT.y(i),streamInter.KNEE_LEFT.z(i)]-...
            [streamInter.ANKLE_LEFT.x(i),streamInter.ANKLE_LEFT.y(i),streamInter.ANKLE_LEFT.z(i)]);
        segments_length.Foot_Left(i) = norm([streamInter.ANKLE_LEFT.x(i),streamInter.ANKLE_LEFT.y(i),streamInter.ANKLE_LEFT.z(i)]-...
            [streamInter.FOOT_LEFT.x(i),streamInter.FOOT_LEFT.y(i),streamInter.FOOT_LEFT.z(i)]);
        
        segments_length.Thigh_Right(i) = norm([streamInter.HIP_RIGHT.x(i),streamInter.HIP_RIGHT.y(i),streamInter.HIP_RIGHT.z(i)]-...
            [streamInter.KNEE_RIGHT.x(i),streamInter.KNEE_RIGHT.y(i),streamInter.KNEE_RIGHT.z(i)]);
        segments_length.Shank_Right(i) = norm([streamInter.KNEE_RIGHT.x(i),streamInter.KNEE_RIGHT.y(i),streamInter.KNEE_RIGHT.z(i)]-...
            [streamInter.ANKLE_RIGHT.x(i),streamInter.ANKLE_RIGHT.y(i),streamInter.ANKLE_RIGHT.z(i)]);
        segments_length.Foot_Right(i) = norm([streamInter.ANKLE_RIGHT.x(i),streamInter.ANKLE_RIGHT.y(i),streamInter.ANKLE_RIGHT.z(i)]-...
            [streamInter.FOOT_RIGHT.x(i),streamInter.FOOT_RIGHT.y(i),streamInter.FOOT_RIGHT.z(i)]);

        segments_length.HeadNeck(i) = norm([streamInter.HEAD.x(i),streamInter.HEAD.y(i),streamInter.HEAD.z(i)]-...
            [streamInter.NECK.x(i),streamInter.NECK.y(i),streamInter.NECK.z(i)]);
        segments_length.Pelvis(i) = norm([streamInter.HIP_LEFT.x(i),streamInter.HIP_LEFT.y(i),streamInter.HIP_LEFT.z(i)]-...
            [streamInter.HIP_RIGHT.x(i),streamInter.HIP_RIGHT.y(i),streamInter.HIP_RIGHT.z(i)]);
        segments_length.Trunk(i) = norm([streamInter.SPINE_CHEST.x(i),streamInter.SPINE_CHEST.y(i),streamInter.SPINE_CHEST.z(i)]-...
            [streamInter.SPINE_NAVAL.x(i),streamInter.SPINE_NAVAL.y(i),streamInter.SPINE_NAVAL.z(i)]);
        
    end
end